name: tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        php: [ '8.3', '8.4', '8.5' ]

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse src tests

    - name: Run test suite
      run: vendor/bin/phpunit -c tests

    - name: Run test linux command
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        php bin/phpvenv venv-bash
        . venv-bash/bin/activate
        php --ini
        deactivate

    - name: Run test powershell command
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        php bin/phpvenv venv-ps
        . venv-ps/Scripts/Activate.ps1
        php --ini
        deactivate

    - name: Run test cmd command
      if: ${{ startsWith(matrix.os, 'windows-') }}
      shell: cmd
      run: |
        php bin/phpvenv venv-cmd
        call venv-cmd/Scripts/activate.bat
        php --ini

